spring.application.name=fronteirapp
spring.datasource.url=jdbc:postgresql://localhost:5432/fronteirapp
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}

#Fase Debug DDL-Auto
#Em Produção Flayway
spring.jpa.hibernate.ddl-auto=update
#imprime o SQL gerado no console modo-debug
spring.jpa.show-sql=true
